version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=thepassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    build:
        context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build: ./backend
    restart: always
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=thepassword
      - DOMAIN=localhost
      - ENVIRONMENT=local
      - PROJECT_NAME="Full Stack FastAPI Project"
      - STACK_NAME=full-stack-fastapi-project
      - BACKEND_CORS_ORIGINS="http://frontend,http://frontend:5173,https://frontend,https://frontend:5173,https://robinsonuche.online,http://robinsonuche.online,http://localhost,http://localhost:8000"
      - SECRET_KEY=changethis123
      - FIRST_SUPERUSER=devops@hng.tech
      - FIRST_SUPERUSER_PASSWORD=devops#HNG11
      - USERS_OPEN_REGISTRATION=True
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    environment:
      - VITE_API_URL=http://frontend:5173
    networks:
      - app-network 
    depends_on:
      - backend

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      #- '80:80'
      - '443:443'
      - '8090:81'
    volumes:
      - npm-data:/data
      - letsencrypt-data:/etc/letsencrypt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  npm-data:
  letsencrypt-data: